[package]
name = "winservice"
version = "0.1.0"
edition = "2021"
build = "./src/build.rs"

[package.metadata.winres]
OriginalFilename = "SERVICE.EXE"

[dependencies]
winapi = "0.3.9"
windows-service = "0.6.0"

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.12"